#!/bin/bash


#../plot_prog.py -db_tag "test_001" -o test_001.pdf $@
#COMMON='-db_engine sqlite -db_name ../database_results/test_smooth_payoff2_100000_16steps_uptol3.db'
COMMON='-db_engine sqlite -db_name ../db/rbergomi_K_1_totally_hierarchical_H_007_steps16.db'

echo "Plotting  1D_BS smooth result  "
../plot_prog.py   -db_tag 'rbergomi_K_1_totally_hierarchical_H_007_steps16' $COMMON  -o rbergomi_K_1_totally_hierarchical_H_007_steps16.pdf  $@




