#!/bin/bash


#../plot_prog.py -db_tag "test_001" -o test_001.pdf $@
#COMMON='-db_engine sqlite -db_name ../database_results/1DBS_2_4steps_smooth_payoff2_richardson.db'
COMMON='-db_engine sqlite -db_name ../db/1DBS_2_4steps_smooth_payoff2_richardson.db'

echo "Plotting  1D_BS smooth result  "
../plot_prog.py   -db_tag '1DBS_2_4steps_smooth_payoff2_richardson' $COMMON  -o 1DBS_2_4steps_smooth_payoff2_richardson.pdf  $@




